# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Execute API and UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test
   
    - name: Upload Test Results
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: karate-summary.html
        # A file, directory or wildcard pattern that describes what to upload
        path: ///home/runner/work/karate-template/karate-template/target/karate-reports/
        # The desired behavior if no files are found using the provided path.

    - name: ANY REPROT - GH Pages Push - SAME REPO
      uses: PavanMudigonda/html-reporter-github-pages@v1.2
      with:
        test_results: ///home/runner/work/karate-template/karate-template/target/karate-reports
        #keep_reports: 20
        gh_pages: gh_pages # BRANCH NAME you like
        #subfolder: docs  # Level 1 Folder Structure you like
        #tool_name: cucumber # Level 2 Folder Structure you like
        #workflow_name: ${{ github.workflow }} # Level 3 Folder Structure you like
        #env: QA # Level 4 Folder Structure you like
        
    #- name: Deploy report page to Github Page
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{secrets.GITHUB_TOKEN}}
    #    publish_dir: ///home/runner/work/karate-template/karate-template/target/karate-reports
      
   
